
#include "common.h"

// Sparse Operations Level 3

// TODO: maybe implement cusparse*csrmm for compatibility

// SPARSE_API_DIRECT(Sbsrmm, please_write,  
//                cusparseDirection_t,      dirA,
//                cusparseOperation_t,      transA,
//                cusparseOperation_t,      transB,
//                int,                      mb,
//                int,                      n,
//                int,                      kb,
//                int,                      nnzb,
//                const float*,             alpha,
//                const cusparseMatDescr_t, descrA,
//                const float*, bsrSortedValA,
//                const int*,   bsrSortedRowPtrA,
//                const int*,   bsrSortedColIndA,
//                const int,    blockSize,
//                const float*, B,
//                const int,    ldb,
//                const float*, beta,
//                float*,       C,
//                int,          ldc)

// SPARSE_API_DIRECT(Dbsrmm, please_write,  
//                cusparseDirection_t,      dirA,
//                cusparseOperation_t,      transA,
//                cusparseOperation_t,      transB,
//                int,                      mb,
//                int,                      n,
//                int,                      kb,
//                int,                      nnzb,
//                const double*,            alpha,
//                const cusparseMatDescr_t, descrA,
//                const double*, bsrSortedValA,
//                const int*,    bsrSortedRowPtrA,
//                const int*,    bsrSortedColIndA,
//                const int,     blockSize,
//                const double*, B,
//                const int,     ldb,
//                const double*, beta,
//                double*,       C,
//                int,           ldc)

// SPARSE_API_DIRECT(Cbsrmm, please_write,  
//                cusparseDirection_t,      dirA,
//                cusparseOperation_t,      transA,
//                cusparseOperation_t,      transB,
//                int,                      mb,
//                int,                      n,
//                int,                      kb,
//                int,                      nnzb,
//                const cuComplex*,         alpha,
//                const cusparseMatDescr_t, descrA,
//                const cuComplex*, bsrSortedValA,
//                const int*,       bsrSortedRowPtrA,
//                const int*,       bsrSortedColIndA,
//                const int,        blockSize,
//                const cuComplex*, B,
//                const int,        ldb,
//                const cuComplex*, beta,
//                cuComplex*,       C,
//                int,              ldc)

// GPUSPARSE_EXPORT_C cusparseStatus_t
//  cusparseZbsrmm(cusparseHandle_t         handle,
//                 cusparseDirection_t      dirA,
//                 cusparseOperation_t      transA,
//                 cusparseOperation_t      transB,
//                 int                      mb,
//                 int                      n,
//                 int                      kb,
//                 int                      nnzb,
//                 const cuDoubleComplex*   alpha,
//                 const cusparseMatDescr_t descrA,
//                 const cuDoubleComplex*   bsrSortedValA,
//                 const int*               bsrSortedRowPtrA,
//                 const int*               bsrSortedColIndA,
//                 const int                blockSize,
//                 const cuDoubleComplex*   B,
//                 const int                ldb,
//                 const cuDoubleComplex*   beta,
//                 cuDoubleComplex*         C,
//                 int                      ldc)

// SPARSE_API_DIRECT(Xbsrsm2_zeroPivot, please_write,   
//                           bsrsm2Info_t,     info,
//                           int*,             position)

// SPARSE_API_DIRECT(Sbsrsm2_bufferSize, please_write,  
//                            cusparseDirection_t,      dirA,
//                            cusparseOperation_t,      transA,
//                            cusparseOperation_t,      transXY,
//                            int,                      mb,
//                            int,                      n,
//                            int,                      nnzb,
//                            const cusparseMatDescr_t, descrA,
//                            float*,                   bsrSortedVal,
//                            const int*,               bsrSortedRowPtr,
//                            const int*,               bsrSortedColInd,
//                            int,                      blockSize,
//                            bsrsm2Info_t,             info,
//                            int*,                     pBufferSizeInBytes)

// SPARSE_API_DIRECT(Dbsrsm2_bufferSize, please_write,  
//                            cusparseDirection_t,      dirA,
//                            cusparseOperation_t,      transA,
//                            cusparseOperation_t,      transXY,
//                            int,                      mb,
//                            int,                      n,
//                            int,                      nnzb,
//                            const cusparseMatDescr_t, descrA,
//                            double*,                  bsrSortedVal,
//                            const int*,               bsrSortedRowPtr,
//                            const int*,               bsrSortedColInd,
//                            int,                      blockSize,
//                            bsrsm2Info_t,             info,
//                            int*,                     pBufferSizeInBytes)

// SPARSE_API_DIRECT(Cbsrsm2_bufferSize, please_write,  
//                            cusparseDirection_t,      dirA,
//                            cusparseOperation_t,      transA,
//                            cusparseOperation_t,      transXY,
//                            int,                      mb,
//                            int,                      n,
//                            int,                      nnzb,
//                            const cusparseMatDescr_t, descrA,
//                            cuComplex*,               bsrSortedVal,
//                            const int*,               bsrSortedRowPtr,
//                            const int*,               bsrSortedColInd,
//                            int,                      blockSize,
//                            bsrsm2Info_t,             info,
//                            int*,                     pBufferSizeInBytes)

// SPARSE_API_DIRECT(Zbsrsm2_bufferSize, please_write,  
//                            cusparseDirection_t,      dirA,
//                            cusparseOperation_t,      transA,
//                            cusparseOperation_t,      transXY,
//                            int,                      mb,
//                            int,                      n,
//                            int,                      nnzb,
//                            const cusparseMatDescr_t, descrA,
//                            cuDoubleComplex*,         bsrSortedVal,
//                            const int*,               bsrSortedRowPtr,
//                            const int*,               bsrSortedColInd,
//                            int,                      blockSize,
//                            bsrsm2Info_t,             info,
//                            int*,                     pBufferSizeInBytes)

// SPARSE_API_DIRECT(Sbsrsm2_bufferSizeExt, please_write,   
//                               cusparseDirection_t,      dirA,
//                               cusparseOperation_t,      transA,
//                               cusparseOperation_t,      transB,
//                               int,                      mb,
//                               int,                      n,
//                               int,                      nnzb,
//                               const cusparseMatDescr_t, descrA,
//                               float*,                   bsrSortedVal,
//                               const int*,               bsrSortedRowPtr,
//                               const int*,               bsrSortedColInd,
//                               int,                      blockSize,
//                               bsrsm2Info_t,             info,
//                               size_t*,                  pBufferSize)

// SPARSE_API_DIRECT(Dbsrsm2_bufferSizeExt, please_write,   
//                               cusparseDirection_t,      dirA,
//                               cusparseOperation_t,      transA,
//                               cusparseOperation_t,      transB,
//                               int,                      mb,
//                               int,                      n,
//                               int,                      nnzb,
//                               const cusparseMatDescr_t, descrA,
//                               double*,                  bsrSortedVal,
//                               const int*,               bsrSortedRowPtr,
//                               const int*,               bsrSortedColInd,
//                               int,                      blockSize,
//                               bsrsm2Info_t,             info,
//                               size_t*,                  pBufferSize)

// SPARSE_API_DIRECT(Cbsrsm2_bufferSizeExt, please_write,   
//                               cusparseDirection_t,      dirA,
//                               cusparseOperation_t,      transA,
//                               cusparseOperation_t,      transB,
//                               int,                      mb,
//                               int,                      n,
//                               int,                      nnzb,
//                               const cusparseMatDescr_t, descrA,
//                               cuComplex*,               bsrSortedVal,
//                               const int*,               bsrSortedRowPtr,
//                               const int*,               bsrSortedColInd,
//                               int,                      blockSize,
//                               bsrsm2Info_t,             info,
//                               size_t*,                  pBufferSize)

// SPARSE_API_DIRECT(Zbsrsm2_bufferSizeExt, please_write,   
//                               cusparseDirection_t,      dirA,
//                               cusparseOperation_t,      transA,
//                               cusparseOperation_t,      transB,
//                               int,                      mb,
//                               int,                      n,
//                               int,                      nnzb,
//                               const cusparseMatDescr_t, descrA,
//                               cuDoubleComplex*,         bsrSortedVal,
//                               const int*,               bsrSortedRowPtr,
//                               const int*,               bsrSortedColInd,
//                               int,                      blockSize,
//                               bsrsm2Info_t,             info,
//                               size_t*,                  pBufferSize)

// SPARSE_API_DIRECT(Sbsrsm2_analysis, please_write,    
//                          cusparseDirection_t,      dirA,
//                          cusparseOperation_t,      transA,
//                          cusparseOperation_t,      transXY,
//                          int,                      mb,
//                          int,                      n,
//                          int,                      nnzb,
//                          const cusparseMatDescr_t, descrA,
//                          const float*,             bsrSortedVal,
//                          const int*,               bsrSortedRowPtr,
//                          const int*,               bsrSortedColInd,
//                          int,                      blockSize,
//                          bsrsm2Info_t,             info,
//                          cusparseSolvePolicy_t,    policy,
//                          void*,                    pBuffer)

// SPARSE_API_DIRECT(Dbsrsm2_analysis, please_write,    
//                          cusparseDirection_t,      dirA,
//                          cusparseOperation_t,      transA,
//                          cusparseOperation_t,      transXY,
//                          int,                      mb,
//                          int,                      n,
//                          int,                      nnzb,
//                          const cusparseMatDescr_t, descrA,
//                          const double*,            bsrSortedVal,
//                          const int*,               bsrSortedRowPtr,
//                          const int*,               bsrSortedColInd,
//                          int,                      blockSize,
//                          bsrsm2Info_t,             info,
//                          cusparseSolvePolicy_t,    policy,
//                          void*,                    pBuffer)

// SPARSE_API_DIRECT(Cbsrsm2_analysis, please_write,    
//                          cusparseDirection_t,      dirA,
//                          cusparseOperation_t,      transA,
//                          cusparseOperation_t,      transXY,
//                          int,                      mb,
//                          int,                      n,
//                          int,                      nnzb,
//                          const cusparseMatDescr_t, descrA,
//                          const cuComplex*,         bsrSortedVal,
//                          const int*,               bsrSortedRowPtr,
//                          const int*,               bsrSortedColInd,
//                          int,                      blockSize,
//                          bsrsm2Info_t,             info,
//                          cusparseSolvePolicy_t,    policy,
//                          void*,                    pBuffer)

// SPARSE_API_DIRECT(Zbsrsm2_analysis, please_write,    
//                          cusparseDirection_t,      dirA,
//                          cusparseOperation_t,      transA,
//                          cusparseOperation_t,      transXY,
//                          int,                      mb,
//                          int,                      n,
//                          int,                      nnzb,
//                          const cusparseMatDescr_t, descrA,
//                          const cuDoubleComplex*,   bsrSortedVal,
//                          const int*,               bsrSortedRowPtr,
//                          const int*,               bsrSortedColInd,
//                          int,                      blockSize,
//                          bsrsm2Info_t,             info,
//                          cusparseSolvePolicy_t,    policy,
//                          void*,                    pBuffer)

// SPARSE_API_DIRECT(Sbsrsm2_solve, please_write,   
//                       cusparseDirection_t,      dirA,
//                       cusparseOperation_t,      transA,
//                       cusparseOperation_t,      transXY,
//                       int,                      mb,
//                       int,                      n,
//                       int,                      nnzb,
//                       const float*,             alpha,
//                       const cusparseMatDescr_t, descrA,
//                       const float*,             bsrSortedVal,
//                       const int*,               bsrSortedRowPtr,
//                       const int*,               bsrSortedColInd,
//                       int,                      blockSize,
//                       bsrsm2Info_t,             info,
//                       const float*,             B,
//                       int,                      ldb,
//                       float*,                   X,
//                       int,                      ldx,
//                       cusparseSolvePolicy_t,    policy,
//                       void*,                    pBuffer)

// SPARSE_API_DIRECT(Dbsrsm2_solve, please_write,   
//                       cusparseDirection_t,      dirA,
//                       cusparseOperation_t,      transA,
//                       cusparseOperation_t,      transXY,
//                       int,                      mb,
//                       int,                      n,
//                       int,                      nnzb,
//                       const double*,            alpha,
//                       const cusparseMatDescr_t, descrA,
//                       const double*,            bsrSortedVal,
//                       const int*,               bsrSortedRowPtr,
//                       const int*,               bsrSortedColInd,
//                       int,                      blockSize,
//                       bsrsm2Info_t,             info,
//                       const double*,            B,
//                       int,                      ldb,
//                       double*,                  X,
//                       int,                      ldx,
//                       cusparseSolvePolicy_t,    policy,
//                       void*,                    pBuffer)

// SPARSE_API_DIRECT(Cbsrsm2_solve, please_write,   
//                       cusparseDirection_t,      dirA,
//                       cusparseOperation_t,      transA,
//                       cusparseOperation_t,      transXY,
//                       int,                      mb,
//                       int,                      n,
//                       int,                      nnzb,
//                       const cuComplex*,         alpha,
//                       const cusparseMatDescr_t, descrA,
//                       const cuComplex*,         bsrSortedVal,
//                       const int*,               bsrSortedRowPtr,
//                       const int*,               bsrSortedColInd,
//                       int,                      blockSize,
//                       bsrsm2Info_t,             info,
//                       const cuComplex*,         B,
//                       int,                      ldb,
//                       cuComplex*,               X,
//                       int,                      ldx,
//                       cusparseSolvePolicy_t,    policy,
//                       void*,                    pBuffer)

// SPARSE_API_DIRECT(Zbsrsm2_solve, please_write,   
//                       cusparseDirection_t,      dirA,
//                       cusparseOperation_t,      transA,
//                       cusparseOperation_t,      transXY,
//                       int,                      mb,
//                       int,                      n,
//                       int,                      nnzb,
//                       const cuDoubleComplex*,   alpha,
//                       const cusparseMatDescr_t, descrA,
//                       const cuDoubleComplex*,   bsrSortedVal,
//                       const int*,               bsrSortedRowPtr,
//                       const int*,               bsrSortedColInd,
//                       int,                      blockSize,
//                       bsrsm2Info_t,             info,
//                       const cuDoubleComplex*,   B,
//                       int,                      ldb,
//                       cuDoubleComplex*,         X,
//                       int,                      ldx,
//                       cusparseSolvePolicy_t,    policy,
//                       void*,                    pBuffer)
