
#include "common.h"
 
/// Preconditioners

// SPARSE_API_DIRECT(Scsrilu02_numericBoost, please_write,  
//                                csrilu02Info_t,   info,
//                                int,              enable_boost,
//                                double*,          tol,
//                                float*,           boost_val);

// SPARSE_API_DIRECT(Dcsrilu02_numericBoost, please_write,  
//                                csrilu02Info_t,   info,
//                                int,              enable_boost,
//                                double*,          tol,
//                                double*,          boost_val);

// SPARSE_API_DIRECT(Ccsrilu02_numericBoost, please_write,  
//                                csrilu02Info_t,   info,
//                                int,              enable_boost,
//                                double*,          tol,
//                                cuComplex*,       boost_val);

// SPARSE_API_DIRECT(Zcsrilu02_numericBoost, please_write,  
//                                csrilu02Info_t,   info,
//                                int,              enable_boost,
//                                double*,          tol,
//                                cuDoubleComplex*, boost_val);

// SPARSE_API_DIRECT(Xcsrilu02_zeroPivot, please_write, 
//                             csrilu02Info_t,   info,
//                             int*,             position);

// SPARSE_API_DIRECT(Scsrilu02_bufferSize, please_write,    
//                              int,                      m,
//                              int,                      nnz,
//                              const cusparseMatDescr_t, descrA,
//                              float*,                   csrSortedValA,
//                              const int*,               csrSortedRowPtrA,
//                              const int*,               csrSortedColIndA,
//                              csrilu02Info_t,           info,
//                              int*,                     pBufferSizeInBytes);

// SPARSE_API_DIRECT(Dcsrilu02_bufferSize, please_write,    
//                              int,                      m,
//                              int,                      nnz,
//                              const cusparseMatDescr_t, descrA,
//                              double*,                  csrSortedValA,
//                              const int*,               csrSortedRowPtrA,
//                              const int*,               csrSortedColIndA,
//                              csrilu02Info_t,           info,
//                              int*,                     pBufferSizeInBytes);

// SPARSE_API_DIRECT(Ccsrilu02_bufferSize, please_write,    
//                              int,                      m,
//                              int,                      nnz,
//                              const cusparseMatDescr_t, descrA,
//                              cuComplex*,               csrSortedValA,
//                              const int*,               csrSortedRowPtrA,
//                              const int*,               csrSortedColIndA,
//                              csrilu02Info_t,           info,
//                              int*,                     pBufferSizeInBytes);

// SPARSE_API_DIRECT(Zcsrilu02_bufferSize, please_write,    
//                              int,                      m,
//                              int,                      nnz,
//                              const cusparseMatDescr_t, descrA,
//                              cuDoubleComplex*,         csrSortedValA,
//                              const int*,               csrSortedRowPtrA,
//                              const int*,               csrSortedColIndA,
//                              csrilu02Info_t,           info,
//                              int*,                     pBufferSizeInBytes);

// SPARSE_API_DIRECT(Scsrilu02_bufferSizeExt, please_write, 
//                                 int,                      m,
//                                 int,                      nnz,
//                                 const cusparseMatDescr_t, descrA,
//                                 float*,                   csrSortedVal,
//                                 const int*,               csrSortedRowPtr,
//                                 const int*,               csrSortedColInd,
//                                 csrilu02Info_t,           info,
//                                 size_t*,                  pBufferSize);

// SPARSE_API_DIRECT(Dcsrilu02_bufferSizeExt, please_write, 
//                                 int,                      m,
//                                 int,                      nnz,
//                                 const cusparseMatDescr_t, descrA,
//                                 double*,                  csrSortedVal,
//                                 const int*,               csrSortedRowPtr,
//                                 const int*,               csrSortedColInd,
//                                 csrilu02Info_t,           info,
//                                 size_t*,                  pBufferSize);

// SPARSE_API_DIRECT(Ccsrilu02_bufferSizeExt, please_write, 
//                                 int,                      m,
//                                 int,                      nnz,
//                                 const cusparseMatDescr_t, descrA,
//                                 cuComplex*,               csrSortedVal,
//                                 const int*,               csrSortedRowPtr,
//                                 const int*,               csrSortedColInd,
//                                 csrilu02Info_t,           info,
//                                 size_t*,                  pBufferSize);

// SPARSE_API_DIRECT(Zcsrilu02_bufferSizeExt, please_write, 
//                                 int,                      m,
//                                 int,                      nnz,
//                                 const cusparseMatDescr_t, descrA,
//                                 cuDoubleComplex*,         csrSortedVal,
//                                 const int*,               csrSortedRowPtr,
//                                 const int*,               csrSortedColInd,
//                                 csrilu02Info_t,           info,
//                                 size_t*,                  pBufferSize);

// SPARSE_API_DIRECT(Scsrilu02_analysis, please_write,  
//                            int,                      m,
//                            int,                      nnz,
//                            const cusparseMatDescr_t, descrA,
//                            const float*,             csrSortedValA,
//                            const int*,               csrSortedRowPtrA,
//                            const int*,               csrSortedColIndA,
//                            csrilu02Info_t,           info,
//                            cusparseSolvePolicy_t,    policy,
//                            void*,                    pBuffer);

// SPARSE_API_DIRECT(Dcsrilu02_analysis, please_write,  
//                            int,                      m,
//                            int,                      nnz,
//                            const cusparseMatDescr_t, descrA,
//                            const double*,            csrSortedValA,
//                            const int*,               csrSortedRowPtrA,
//                            const int*,               csrSortedColIndA,
//                            csrilu02Info_t,           info,
//                            cusparseSolvePolicy_t,    policy,
//                            void*,                    pBuffer);

// SPARSE_API_DIRECT(Ccsrilu02_analysis, please_write,  
//                            int,                      m,
//                            int,                      nnz,
//                            const cusparseMatDescr_t, descrA,
//                            const cuComplex*,         csrSortedValA,
//                            const int*,               csrSortedRowPtrA,
//                            const int*,               csrSortedColIndA,
//                            csrilu02Info_t,           info,
//                            cusparseSolvePolicy_t,    policy,
//                            void*,                    pBuffer);

// SPARSE_API_DIRECT(Zcsrilu02_analysis, please_write,  
//                            int,                      m,
//                            int,                      nnz,
//                            const cusparseMatDescr_t, descrA,
//                            const cuDoubleComplex*,   csrSortedValA,
//                            const int*,               csrSortedRowPtrA,
//                            const int*,               csrSortedColIndA,
//                            csrilu02Info_t,           info,
//                            cusparseSolvePolicy_t,    policy,
//                            void*,                    pBuffer);

// SPARSE_API_DIRECT(Scsrilu02, please_write,   
//                   int,                      m,
//                   int,                      nnz,
//                   const cusparseMatDescr_t, descrA,
//                   float*,                   csrSortedValA_valM,
//                   const int*,            csrSortedRowPtrA,
//                   const int*,            csrSortedColIndA,
//                   csrilu02Info_t,        info,
//                   cusparseSolvePolicy_t, policy,
//                   void*,                 pBuffer);

// SPARSE_API_DIRECT(Dcsrilu02, please_write,   
//                   int,                      m,
//                   int,                      nnz,
//                   const cusparseMatDescr_t, descrA,
//                   double*,                  csrSortedValA_valM,
//                   const int*,            csrSortedRowPtrA,
//                   const int*,            csrSortedColIndA,
//                   csrilu02Info_t,        info,
//                   cusparseSolvePolicy_t, policy,
//                   void*,                 pBuffer);

// SPARSE_API_DIRECT(Ccsrilu02, please_write,   
//                   int,                      m,
//                   int,                      nnz,
//                   const cusparseMatDescr_t, descrA,
//                   cuComplex*,               csrSortedValA_valM,
//                   const int*,            csrSortedRowPtrA,
//                   const int*,            csrSortedColIndA,
//                   csrilu02Info_t,        info,
//                   cusparseSolvePolicy_t, policy,
//                   void*,                 pBuffer);

// SPARSE_API_DIRECT(Zcsrilu02, please_write,   
//                   int,                      m,
//                   int,                      nnz,
//                   const cusparseMatDescr_t, descrA,
//                   cuDoubleComplex*,         csrSortedValA_valM,
//                   const int*,            csrSortedRowPtrA,
//                   const int*,            csrSortedColIndA,
//                   csrilu02Info_t,        info,
//                   cusparseSolvePolicy_t, policy,
//                   void*,                 pBuffer);

// SPARSE_API_DIRECT(Sbsrilu02_numericBoost, please_write,  
//                                bsrilu02Info_t,   info,
//                                int,              enable_boost,
//                                double*,          tol,
//                                float*,           boost_val);

// SPARSE_API_DIRECT(Dbsrilu02_numericBoost, please_write,  
//                                bsrilu02Info_t,   info,
//                                int,              enable_boost,
//                                double*,          tol,
//                                double*,          boost_val);

// SPARSE_API_DIRECT(Cbsrilu02_numericBoost, please_write,  
//                                bsrilu02Info_t,   info,
//                                int,              enable_boost,
//                                double*,          tol,
//                                cuComplex*,       boost_val);

// SPARSE_API_DIRECT(Zbsrilu02_numericBoost, please_write,  
//                                bsrilu02Info_t,   info,
//                                int,              enable_boost,
//                                double*,          tol,
//                                cuDoubleComplex*, boost_val);

// SPARSE_API_DIRECT(Xbsrilu02_zeroPivot, please_write, 
//                             bsrilu02Info_t,   info,
//                             int*,             position);

// SPARSE_API_DIRECT(Sbsrilu02_bufferSize, please_write,    
//                              cusparseDirection_t,      dirA,
//                              int,                      mb,
//                              int,                      nnzb,
//                              const cusparseMatDescr_t, descrA,
//                              float*,                   bsrSortedVal,
//                              const int*,               bsrSortedRowPtr,
//                              const int*,               bsrSortedColInd,
//                              int,                      blockDim,
//                              bsrilu02Info_t,           info,
//                              int*,                     pBufferSizeInBytes);

// SPARSE_API_DIRECT(Dbsrilu02_bufferSize, please_write,    
//                              cusparseDirection_t,      dirA,
//                              int,                      mb,
//                              int,                      nnzb,
//                              const cusparseMatDescr_t, descrA,
//                              double*,                  bsrSortedVal,
//                              const int*,               bsrSortedRowPtr,
//                              const int*,               bsrSortedColInd,
//                              int,                      blockDim,
//                              bsrilu02Info_t,           info,
//                              int*,                     pBufferSizeInBytes);

// SPARSE_API_DIRECT(Cbsrilu02_bufferSize, please_write,    
//                              cusparseDirection_t,      dirA,
//                              int,                      mb,
//                              int,                      nnzb,
//                              const cusparseMatDescr_t, descrA,
//                              cuComplex*,               bsrSortedVal,
//                              const int*,               bsrSortedRowPtr,
//                              const int*,               bsrSortedColInd,
//                              int,                      blockDim,
//                              bsrilu02Info_t,           info,
//                              int*,                     pBufferSizeInBytes);

// SPARSE_API_DIRECT(Zbsrilu02_bufferSize, please_write,    
//                              cusparseDirection_t,      dirA,
//                              int,                      mb,
//                              int,                      nnzb,
//                              const cusparseMatDescr_t, descrA,
//                              cuDoubleComplex*,         bsrSortedVal,
//                              const int*,               bsrSortedRowPtr,
//                              const int*,               bsrSortedColInd,
//                              int,                      blockDim,
//                              bsrilu02Info_t,           info,
//                              int*,                     pBufferSizeInBytes);

// SPARSE_API_DIRECT(Sbsrilu02_bufferSizeExt, please_write, 
//                                 cusparseDirection_t,      dirA,
//                                 int,                      mb,
//                                 int,                      nnzb,
//                                 const cusparseMatDescr_t, descrA,
//                                 float*,                   bsrSortedVal,
//                                 const int*,               bsrSortedRowPtr,
//                                 const int*,               bsrSortedColInd,
//                                 int,                      blockSize,
//                                 bsrilu02Info_t,           info,
//                                 size_t*,                  pBufferSize);

// SPARSE_API_DIRECT(Dbsrilu02_bufferSizeExt, please_write, 
//                                 cusparseDirection_t,      dirA,
//                                 int,                      mb,
//                                 int,                      nnzb,
//                                 const cusparseMatDescr_t, descrA,
//                                 double*,                  bsrSortedVal,
//                                 const int*,               bsrSortedRowPtr,
//                                 const int*,               bsrSortedColInd,
//                                 int,                      blockSize,
//                                 bsrilu02Info_t,           info,
//                                 size_t*,                  pBufferSize);

// SPARSE_API_DIRECT(Cbsrilu02_bufferSizeExt, please_write, 
//                                 cusparseDirection_t,      dirA,
//                                 int,                      mb,
//                                 int,                      nnzb,
//                                 const cusparseMatDescr_t, descrA,
//                                 cuComplex*,               bsrSortedVal,
//                                 const int*,               bsrSortedRowPtr,
//                                 const int*,               bsrSortedColInd,
//                                 int,                      blockSize,
//                                 bsrilu02Info_t,           info,
//                                 size_t*,                  pBufferSize);

// SPARSE_API_DIRECT(Zbsrilu02_bufferSizeExt, please_write, 
//                                cusparseDirection_t,      dirA,
//                                int,                      mb,
//                                int,                      nnzb,
//                                const cusparseMatDescr_t, descrA,
//                                cuDoubleComplex*,         bsrSortedVal,
//                                const int*,               bsrSortedRowPtr,
//                                const int*,               bsrSortedColInd,
//                                int,                      blockSize,
//                                bsrilu02Info_t,           info,
//                                size_t*,                  pBufferSize);

// SPARSE_API_DIRECT(Sbsrilu02_analysis, please_write,  
//                            cusparseDirection_t,      dirA,
//                            int,                      mb,
//                            int,                      nnzb,
//                            const cusparseMatDescr_t, descrA,
//                            float*,                   bsrSortedVal,
//                            const int*,               bsrSortedRowPtr,
//                            const int*,               bsrSortedColInd,
//                            int,                      blockDim,
//                            bsrilu02Info_t,           info,
//                            cusparseSolvePolicy_t,    policy,
//                            void*,                    pBuffer);

// SPARSE_API_DIRECT(Dbsrilu02_analysis, please_write,  
//                            cusparseDirection_t,      dirA,
//                            int,                      mb,
//                            int,                      nnzb,
//                            const cusparseMatDescr_t, descrA,
//                            double*,                  bsrSortedVal,
//                            const int*,               bsrSortedRowPtr,
//                            const int*,               bsrSortedColInd,
//                            int,                      blockDim,
//                            bsrilu02Info_t,           info,
//                            cusparseSolvePolicy_t,    policy,
//                            void*,                    pBuffer);

// SPARSE_API_DIRECT(Cbsrilu02_analysis, please_write,  
//                            cusparseDirection_t,      dirA,
//                            int,                      mb,
//                            int,                      nnzb,
//                            const cusparseMatDescr_t, descrA,
//                            cuComplex*,               bsrSortedVal,
//                            const int*,               bsrSortedRowPtr,
//                            const int*,               bsrSortedColInd,
//                            int,                      blockDim,
//                            bsrilu02Info_t,           info,
//                            cusparseSolvePolicy_t,    policy,
//                            void*,                    pBuffer);

// SPARSE_API_DIRECT(Zbsrilu02_analysis, please_write,  
//                            cusparseDirection_t,      dirA,
//                            int,                      mb,
//                            int,                      nnzb,
//                            const cusparseMatDescr_t, descrA,
//                            cuDoubleComplex*,         bsrSortedVal,
//                            const int*,               bsrSortedRowPtr,
//                            const int*,               bsrSortedColInd,
//                            int,                      blockDim,
//                            bsrilu02Info_t,           info,
//                            cusparseSolvePolicy_t,    policy,
//                            void*,                    pBuffer);

// SPARSE_API_DIRECT(Sbsrilu02, please_write,   
//                   cusparseDirection_t,      dirA,
//                   int,                      mb,
//                   int,                      nnzb,
//                   const cusparseMatDescr_t, descrA,
//                   float*,                   bsrSortedVal,
//                   const int*,               bsrSortedRowPtr,
//                   const int*,               bsrSortedColInd,
//                   int,                      blockDim,
//                   bsrilu02Info_t,           info,
//                   cusparseSolvePolicy_t,    policy,
//                   void*,                    pBuffer);

// SPARSE_API_DIRECT(Dbsrilu02, please_write,   
//                   cusparseDirection_t,      dirA,
//                   int,                      mb,
//                   int,                      nnzb,
//                   const cusparseMatDescr_t, descrA,
//                   double*,                  bsrSortedVal,
//                   const int*,               bsrSortedRowPtr,
//                   const int*,               bsrSortedColInd,
//                   int,                      blockDim,
//                   bsrilu02Info_t,           info,
//                   cusparseSolvePolicy_t,    policy,
//                   void*,                    pBuffer);

// SPARSE_API_DIRECT(Cbsrilu02, please_write,   
//                   cusparseDirection_t,      dirA,
//                   int,                      mb,
//                   int,                      nnzb,
//                   const cusparseMatDescr_t, descrA,
//                   cuComplex*,               bsrSortedVal,
//                   const int*,               bsrSortedRowPtr,
//                   const int*,               bsrSortedColInd,
//                   int,                      blockDim,
//                   bsrilu02Info_t,           info,
//                   cusparseSolvePolicy_t,    policy,
//                   void*,                    pBuffer);

// SPARSE_API_DIRECT(Zbsrilu02, please_write,   
//                   cusparseDirection_t,      dirA,
//                   int,                      mb,
//                   int,                      nnzb,
//                   const cusparseMatDescr_t, descrA,
//                   cuDoubleComplex*,         bsrSortedVal,
//                   const int*,               bsrSortedRowPtr,
//                   const int*,               bsrSortedColInd,
//                   int,                      blockDim,
//                   bsrilu02Info_t,           info,
//                   cusparseSolvePolicy_t,    policy,
//                   void*,                    pBuffer);

// SPARSE_API_DIRECT(Xcsric02_zeroPivot, please_write,  
//                            csric02Info_t,    info,
//                            int*,             position);

// SPARSE_API_DIRECT(Scsric02_bufferSize, please_write, 
//                             int,                      m,
//                             int,                      nnz,
//                             const cusparseMatDescr_t, descrA,
//                             float*,                   csrSortedValA,
//                             const int*,               csrSortedRowPtrA,
//                             const int*,               csrSortedColIndA,
//                             csric02Info_t,            info,
//                             int*,                     pBufferSizeInBytes);

// SPARSE_API_DIRECT(Dcsric02_bufferSize, please_write, 
//                             int,                      m,
//                             int,                      nnz,
//                             const cusparseMatDescr_t, descrA,
//                             double*,                  csrSortedValA,
//                             const int*,               csrSortedRowPtrA,
//                             const int*,               csrSortedColIndA,
//                             csric02Info_t,            info,
//                             int*,                     pBufferSizeInBytes);

// SPARSE_API_DIRECT(Ccsric02_bufferSize, please_write, 
//                             int,                      m,
//                             int,                      nnz,
//                             const cusparseMatDescr_t, descrA,
//                             cuComplex*,               csrSortedValA,
//                             const int*,               csrSortedRowPtrA,
//                             const int*,               csrSortedColIndA,
//                             csric02Info_t,            info,
//                             int*,                     pBufferSizeInBytes);

// SPARSE_API_DIRECT(Zcsric02_bufferSize, please_write, 
//                             int,                      m,
//                             int,                      nnz,
//                             const cusparseMatDescr_t, descrA,
//                             cuDoubleComplex*,         csrSortedValA,
//                             const int*,               csrSortedRowPtrA,
//                             const int*,               csrSortedColIndA,
//                             csric02Info_t,            info,
//                             int*,                     pBufferSizeInBytes);

// SPARSE_API_DIRECT(Scsric02_bufferSizeExt, please_write,  
//                                int,                      m,
//                                int,                      nnz,
//                                const cusparseMatDescr_t, descrA,
//                                float*,                   csrSortedVal,
//                                const int*,               csrSortedRowPtr,
//                                const int*,               csrSortedColInd,
//                                csric02Info_t,            info,
//                                size_t*,                  pBufferSize);

// SPARSE_API_DIRECT(Dcsric02_bufferSizeExt, please_write,  
//                                int,                      m,
//                                int,                      nnz,
//                                const cusparseMatDescr_t, descrA,
//                                double*,                  csrSortedVal,
//                                const int*,               csrSortedRowPtr,
//                                const int*,               csrSortedColInd,
//                                csric02Info_t,            info,
//                                size_t*,                  pBufferSize);

// SPARSE_API_DIRECT(Ccsric02_bufferSizeExt, please_write,  
//                                int,                      m,
//                                int,                      nnz,
//                                const cusparseMatDescr_t, descrA,
//                                cuComplex*,               csrSortedVal,
//                                const int*,               csrSortedRowPtr,
//                                const int*,               csrSortedColInd,
//                                csric02Info_t,            info,
//                                size_t*,                  pBufferSize);

// SPARSE_API_DIRECT(Zcsric02_bufferSizeExt, please_write,  
//                                int,                      m,
//                                int,                      nnz,
//                                const cusparseMatDescr_t, descrA,
//                                cuDoubleComplex*,         csrSortedVal,
//                                const int*,               csrSortedRowPtr,
//                                const int*,               csrSortedColInd,
//                                csric02Info_t,            info,
//                                size_t*,                  pBufferSize);

// SPARSE_API_DIRECT(Scsric02_analysis, please_write,   
//                           int,                      m,
//                           int,                      nnz,
//                           const cusparseMatDescr_t, descrA,
//                           const float*,             csrSortedValA,
//                           const int*,               csrSortedRowPtrA,
//                           const int*,               csrSortedColIndA,
//                           csric02Info_t,            info,
//                           cusparseSolvePolicy_t,    policy,
//                           void*,                    pBuffer);

// SPARSE_API_DIRECT(Dcsric02_analysis, please_write,   
//                           int,                      m,
//                           int,                      nnz,
//                           const cusparseMatDescr_t, descrA,
//                           const double*,            csrSortedValA,
//                           const int*,               csrSortedRowPtrA,
//                           const int*,               csrSortedColIndA,
//                           csric02Info_t,            info,
//                           cusparseSolvePolicy_t,    policy,
//                           void*,                    pBuffer);

// SPARSE_API_DIRECT(Ccsric02_analysis, please_write,   
//                           int,                      m,
//                           int,                      nnz,
//                           const cusparseMatDescr_t, descrA,
//                           const cuComplex*,         csrSortedValA,
//                           const int*,               csrSortedRowPtrA,
//                           const int*,               csrSortedColIndA,
//                           csric02Info_t,            info,
//                           cusparseSolvePolicy_t,    policy,
//                           void*,                    pBuffer);

// SPARSE_API_DIRECT(Zcsric02_analysis, please_write,   
//                           int,                      m,
//                           int,                      nnz,
//                           const cusparseMatDescr_t, descrA,
//                           const cuDoubleComplex*,   csrSortedValA,
//                           const int*,               csrSortedRowPtrA,
//                           const int*,               csrSortedColIndA,
//                           csric02Info_t,            info,
//                           cusparseSolvePolicy_t,    policy,
//                           void*,                    pBuffer);

// SPARSE_API_DIRECT(Scsric02, please_write,    
//                  int,                      m,
//                  int,                      nnz,
//                  const cusparseMatDescr_t, descrA,
//                  float*,                   csrSortedValA_valM,
//                  const int*,               csrSortedRowPtrA,
//                  const int*,               csrSortedColIndA,
//                  csric02Info_t,            info,
//                  cusparseSolvePolicy_t,    policy,
//                  void*,                    pBuffer);

// SPARSE_API_DIRECT(Dcsric02, please_write,    
//                  int,                      m,
//                  int,                      nnz,
//                  const cusparseMatDescr_t, descrA,
//                  double*,                  csrSortedValA_valM,
//                  const int*,               csrSortedRowPtrA,
//                  const int*,               csrSortedColIndA,
//                  csric02Info_t,            info,
//                  cusparseSolvePolicy_t,    policy,
//                  void*,                    pBuffer);

// SPARSE_API_DIRECT(Ccsric02, please_write,    
//                  int,                      m,
//                  int,                      nnz,
//                  const cusparseMatDescr_t, descrA,
//                  cuComplex*,               csrSortedValA_valM,
//                  const int*,               csrSortedRowPtrA,
//                  const int*,               csrSortedColIndA,
//                  csric02Info_t,            info,
//                  cusparseSolvePolicy_t,    policy,
//                  void*,                    pBuffer);

// SPARSE_API_DIRECT(Zcsric02, please_write,    
//                  int,                      m,
//                  int,                      nnz,
//                  const cusparseMatDescr_t, descrA,
//                  cuDoubleComplex*,         csrSortedValA_valM,
//                  const int*,               csrSortedRowPtrA,
//                  const int*,               csrSortedColIndA,
//                  csric02Info_t,            info,
//                  cusparseSolvePolicy_t,    policy,
//                  void*,                    pBuffer);

// SPARSE_API_DIRECT(Xbsric02_zeroPivot, please_write,  
//                            bsric02Info_t,    info,
//                            int*,             position);

// SPARSE_API_DIRECT(Sbsric02_bufferSize, please_write, 
//                             cusparseDirection_t,      dirA,
//                             int,                      mb,
//                             int,                      nnzb,
//                             const cusparseMatDescr_t, descrA,
//                             float*,                   bsrSortedVal,
//                             const int*,               bsrSortedRowPtr,
//                             const int*,               bsrSortedColInd,
//                             int,                      blockDim,
//                             bsric02Info_t,            info,
//                             int*,                     pBufferSizeInBytes);

// SPARSE_API_DIRECT(Dbsric02_bufferSize, please_write, 
//                             cusparseDirection_t,      dirA,
//                             int,                      mb,
//                             int,                      nnzb,
//                             const cusparseMatDescr_t, descrA,
//                             double*,                  bsrSortedVal,
//                             const int*,               bsrSortedRowPtr,
//                             const int*,               bsrSortedColInd,
//                             int,                      blockDim,
//                             bsric02Info_t,            info,
//                             int*,                     pBufferSizeInBytes);

// SPARSE_API_DIRECT(Cbsric02_bufferSize, please_write, 
//                             cusparseDirection_t,      dirA,
//                             int,                      mb,
//                             int,                      nnzb,
//                             const cusparseMatDescr_t, descrA,
//                             cuComplex*,               bsrSortedVal,
//                             const int*,               bsrSortedRowPtr,
//                             const int*,               bsrSortedColInd,
//                             int,                      blockDim,
//                             bsric02Info_t,            info,
//                             int*,                     pBufferSizeInBytes);

// SPARSE_API_DIRECT(Zbsric02_bufferSize, please_write, 
//                             cusparseDirection_t,      dirA,
//                             int,                      mb,
//                             int,                      nnzb,
//                             const cusparseMatDescr_t, descrA,
//                             cuDoubleComplex*,         bsrSortedVal,
//                             const int*,               bsrSortedRowPtr,
//                             const int*,               bsrSortedColInd,
//                             int,                      blockDim,
//                             bsric02Info_t,            info,
//                             int*,                     pBufferSizeInBytes);

// SPARSE_API_DIRECT(Sbsric02_bufferSizeExt, please_write,  
//                                cusparseDirection_t,      dirA,
//                                int,                      mb,
//                                int,                      nnzb,
//                                const cusparseMatDescr_t, descrA,
//                                float*,                   bsrSortedVal,
//                                const int*,               bsrSortedRowPtr,
//                                const int*,               bsrSortedColInd,
//                                int,                      blockSize,
//                                bsric02Info_t,            info,
//                                size_t*,                  pBufferSize);

// SPARSE_API_DIRECT(Dbsric02_bufferSizeExt, please_write,  
//                                cusparseDirection_t,      dirA,
//                                int,                      mb,
//                                int,                      nnzb,
//                                const cusparseMatDescr_t, descrA,
//                                double*,                  bsrSortedVal,
//                                const int*,               bsrSortedRowPtr,
//                                const int*,               bsrSortedColInd,
//                                int,                      blockSize,
//                                bsric02Info_t,            info,
//                                size_t*,                  pBufferSize);

// SPARSE_API_DIRECT(Cbsric02_bufferSizeExt, please_write,  
//                                cusparseDirection_t,      dirA,
//                                int,                      mb,
//                                int,                      nnzb,
//                                const cusparseMatDescr_t, descrA,
//                                cuComplex*,               bsrSortedVal,
//                                const int*,               bsrSortedRowPtr,
//                                const int*,               bsrSortedColInd,
//                                int,                      blockSize,
//                                bsric02Info_t,            info,
//                                size_t*,                  pBufferSize);

// SPARSE_API_DIRECT(Zbsric02_bufferSizeExt, please_write,  
//                                cusparseDirection_t,      dirA,
//                                int,                      mb,
//                                int,                      nnzb,
//                                const cusparseMatDescr_t, descrA,
//                                cuDoubleComplex*,         bsrSortedVal,
//                                const int*,               bsrSortedRowPtr,
//                                const int*,               bsrSortedColInd,
//                                int,                      blockSize,
//                                bsric02Info_t,            info,
//                                size_t*,                  pBufferSize);

// SPARSE_API_DIRECT(Sbsric02_analysis, please_write,   
//                           cusparseDirection_t,      dirA,
//                           int,                      mb,
//                           int,                      nnzb,
//                           const cusparseMatDescr_t, descrA,
//                           const float*,             bsrSortedVal,
//                           const int*,               bsrSortedRowPtr,
//                           const int*,               bsrSortedColInd,
//                           int,                      blockDim,
//                           bsric02Info_t,            info,
//                           cusparseSolvePolicy_t,    policy,
//                           void*,                    pInputBuffer);

// SPARSE_API_DIRECT(Dbsric02_analysis, please_write,   
//                           cusparseDirection_t,      dirA,
//                           int,                      mb,
//                           int,                      nnzb,
//                           const cusparseMatDescr_t, descrA,
//                           const double*,            bsrSortedVal,
//                           const int*,               bsrSortedRowPtr,
//                           const int*,               bsrSortedColInd,
//                           int,                      blockDim,
//                           bsric02Info_t,            info,
//                           cusparseSolvePolicy_t,    policy,
//                           void*,                    pInputBuffer);

// SPARSE_API_DIRECT(Cbsric02_analysis, please_write,   
//                           cusparseDirection_t,      dirA,
//                           int,                      mb,
//                           int,                      nnzb,
//                           const cusparseMatDescr_t, descrA,
//                           const cuComplex*,         bsrSortedVal,
//                           const int*,               bsrSortedRowPtr,
//                           const int*,               bsrSortedColInd,
//                           int,                      blockDim,
//                           bsric02Info_t,            info,
//                           cusparseSolvePolicy_t,    policy,
//                           void*,                    pInputBuffer);

// SPARSE_API_DIRECT(Zbsric02_analysis, please_write,   
//                           cusparseDirection_t,      dirA,
//                           int,                      mb,
//                           int,                      nnzb,
//                           const cusparseMatDescr_t, descrA,
//                           const cuDoubleComplex*,   bsrSortedVal,
//                           const int*,               bsrSortedRowPtr,
//                           const int*,               bsrSortedColInd,
//                           int,                      blockDim,
//                           bsric02Info_t,            info,
//                           cusparseSolvePolicy_t,    policy,
//                           void*,                    pInputBuffer);

// SPARSE_API_DIRECT(Sbsric02, please_write,    
//                  cusparseDirection_t,      dirA,
//                  int,                      mb,
//                  int,                      nnzb,
//                  const cusparseMatDescr_t, descrA,
//                  float*,                   bsrSortedVal,
//                  const int*,               bsrSortedRowPtr,
//                  const int*,               bsrSortedColInd,
//                  int,                      blockDim,
//                  bsric02Info_t,            info,
//                  cusparseSolvePolicy_t,    policy,
//                  void*,                    pBuffer);

// SPARSE_API_DIRECT(Dbsric02, please_write,    
//                  cusparseDirection_t,      dirA,
//                  int,                      mb,
//                  int,                      nnzb,
//                  const cusparseMatDescr_t, descrA,
//                  double*,                  bsrSortedVal,
//                  const int*,               bsrSortedRowPtr,
//                  const int*,               bsrSortedColInd,
//                  int,                      blockDim,
//                  bsric02Info_t,            info,
//                  cusparseSolvePolicy_t,    policy,
//                  void*,                    pBuffer);

// SPARSE_API_DIRECT(Cbsric02, please_write,    
//                  cusparseDirection_t,      dirA,
//                  int,                      mb,
//                  int,                      nnzb,
//                  const cusparseMatDescr_t, descrA,
//                  cuComplex*,               bsrSortedVal,
//                  const int*,               bsrSortedRowPtr,
//                  const int*,
//                       bsrSortedColInd,
//                  int,                      blockDim,
//                  bsric02Info_t,            info,
//                  cusparseSolvePolicy_t,    policy,
//                  void*,                    pBuffer);

// SPARSE_API_DIRECT(Zbsric02, please_write,    
//                  cusparseDirection_t,      dirA,
//                  int,                      mb,
//                  int,                      nnzb,
//                  const cusparseMatDescr_t, descrA,
//                  cuDoubleComplex*,         bsrSortedVal,
//                  const int*,               bsrSortedRowPtr,
//                  const int*,               bsrSortedColInd,
//                  int,                      blockDim,
//                  bsric02Info_t,            info,
//                  cusparseSolvePolicy_t,    policy,
//                  void*,                    pBuffer);

// SPARSE_API_DIRECT(Sgtsv2_bufferSizeExt, please_write,    
//                              int,              m,
//                              int,              n,
//                              const float*,     dl,
//                              const float*,     d,
//                              const float*,     du,
//                              const float*,     B,
//                              int,              ldb,
//                              size_t*,          bufferSizeInBytes);

// SPARSE_API_DIRECT(Dgtsv2_bufferSizeExt, please_write,    
//                              int,              m,
//                              int,              n,
//                              const double*,    dl,
//                              const double*,    d,
//                              const double*,    du,
//                              const double*,    B,
//                              int,              ldb,
//                              size_t*,          bufferSizeInBytes);

// SPARSE_API_DIRECT(Cgtsv2_bufferSizeExt, please_write,    
//                              int,              m,
//                              int,              n,
//                              const cuComplex*, dl,
//                              const cuComplex*, d,
//                              const cuComplex*, du,
//                              const cuComplex*, B,
//                              int,              ldb,
//                              size_t*,          bufferSizeInBytes);

// SPARSE_API_DIRECT(Zgtsv2_bufferSizeExt, please_write,    
//                              int,                    m,
//                              int,                    n,
//                              const cuDoubleComplex*, dl,
//                              const cuDoubleComplex*, d,
//                              const cuDoubleComplex*, du,
//                              const cuDoubleComplex*, B,
//                              int,                    ldb,
//                              size_t*,                bufferSizeInBytes);

// SPARSE_API_DIRECT(Sgtsv2, please_write,  
//                int,              m,
//                int,              n,
//                const float*,     dl,
//                const float*,     d,
//                const float*,     du,
//                float*,           B,
//                int,              ldb,
//                void*,            pBuffer);

// SPARSE_API_DIRECT(Dgtsv2, please_write,  
//                int,              m,
//                int,              n,
//                const double*,    dl,
//                const double*,    d,
//                const double*,    du,
//                double*,          B,
//                int,              ldb,
//                void*,            pBuffer);

// SPARSE_API_DIRECT(Cgtsv2, please_write,  
//                int,              m,
//                int,              n,
//                const cuComplex*, dl,
//                const cuComplex*, d,
//                const cuComplex*, du,
//                cuComplex*,       B,
//                int,              ldb,
//                void*,            pBuffer);

// SPARSE_API_DIRECT(Zgtsv2, please_write,  
//                int,                    m,
//                int,                    n,
//                const cuDoubleComplex*, dl,
//                const cuDoubleComplex*, d,
//                const cuDoubleComplex*, du,
//                cuDoubleComplex*,       B,
//                int,                    ldb,
//                void*,                  pBuffer);

// SPARSE_API_DIRECT(Sgtsv2_nopivot_bufferSizeExt, please_write,    
//                                      int,              m,
//                                      int,              n,
//                                      const float*,     dl,
//                                      const float*,     d,
//                                      const float*,     du,
//                                      const float*,     B,
//                                      int,              ldb,
//                                      size_t*,          bufferSizeInBytes);

// SPARSE_API_DIRECT(Dgtsv2_nopivot_bufferSizeExt, please_write,    
//                                      int,              m,
//                                      int,              n,
//                                      const double*,    dl,
//                                      const double*,    d,
//                                      const double*,    du,
//                                      const double*,    B,
//                                      int,              ldb,
//                                      size_t*,          bufferSizeInBytes);

// SPARSE_API_DIRECT(Cgtsv2_nopivot_bufferSizeExt, please_write,    
//                                      int,              m,
//                                      int,              n,
//                                      const cuComplex*, dl,
//                                      const cuComplex*, d,
//                                      const cuComplex*, du,
//                                      const cuComplex*, B,
//                                      int,              ldb,
//                                      size_t*,          bufferSizeInBytes);

// SPARSE_API_DIRECT(Zgtsv2_nopivot_bufferSizeExt, please_write,    
//                                      int,                    m,
//                                      int,                    n,
//                                      const cuDoubleComplex*, dl,
//                                      const cuDoubleComplex*, d,
//                                      const cuDoubleComplex*, du,
//                                      const cuDoubleComplex*, B,
//                                      int,                    ldb,
//                                      size_t*,                bufferSizeInBytes);

// SPARSE_API_DIRECT(Sgtsv2_nopivot, please_write,  
//                        int,              m,
//                        int,              n,
//                        const float*,     dl,
//                        const float*,     d,
//                        const float*,     du,
//                        float*,           B,
//                        int,              ldb,
//                        void*,            pBuffer);

// SPARSE_API_DIRECT(Dgtsv2_nopivot, please_write,  
//                        int,              m,
//                        int,              n,
//                        const double*,    dl,
//                        const double*,    d,
//                        const double*,    du,
//                        double*,          B,
//                        int,              ldb,
//                        void*,            pBuffer);

// SPARSE_API_DIRECT(Cgtsv2_nopivot, please_write,  
//                        int,              m,
//                        int,              n,
//                        const cuComplex*, dl,
//                        const cuComplex*, d,
//                        const cuComplex*, du,
//                        cuComplex*,       B,
//                        int,              ldb,
//                        void*,            pBuffer);

// SPARSE_API_DIRECT(Zgtsv2_nopivot, please_write,  
//                        int,                    m,
//                        int,                    n,
//                        const cuDoubleComplex*, dl,
//                        const cuDoubleComplex*, d,
//                        const cuDoubleComplex*, du,
//                        cuDoubleComplex*,       B,
//                        int,                    ldb,
//                        void*,                  pBuffer);

// SPARSE_API_DIRECT(Sgtsv2StridedBatch_bufferSizeExt, please_write,    
//                                          int,              m,
//                                          const float*,     dl,
//                                          const float*,     d,
//                                          const float*,     du,
//                                          const float*,     x,
//                                          int,              batchCount,
//                                          int,              batchStride,
//                                          size_t*,          bufferSizeInBytes);

// SPARSE_API_DIRECT(Dgtsv2StridedBatch_bufferSizeExt, please_write,    
//                                          int,              m,
//                                          const double*,    dl,
//                                          const double*,    d,
//                                          const double*,    du,
//                                          const double*,    x,
//                                          int,              batchCount,
//                                          int,              batchStride,
//                                          size_t*,          bufferSizeInBytes);

// SPARSE_API_DIRECT(Cgtsv2StridedBatch_bufferSizeExt, please_write,    
//                                          int,              m,
//                                          const cuComplex*, dl,
//                                          const cuComplex*, d,
//                                          const cuComplex*, du,
//                                          const cuComplex*, x,
//                                          int,              batchCount,
//                                          int,              batchStride,
//                                          size_t*,          bufferSizeInBytes);

// SPARSE_API_DIRECT(Zgtsv2StridedBatch_bufferSizeExt, please_write,    
//                                          int,                    m,
//                                          const cuDoubleComplex*, dl,
//                                          const cuDoubleComplex*, d,
//                                          const cuDoubleComplex*, du,
//                                          const cuDoubleComplex*, x,
//                                          int,                    batchCount,
//                                          int,                    batchStride,
//                                          size_t*, bufferSizeInBytes);

// SPARSE_API_DIRECT(Sgtsv2StridedBatch, please_write,  
//                            int,              m,
//                            const float*,     dl,
//                            const float*,     d,
//                            const float*,     du,
//                            float*,           x,
//                            int,              batchCount,
//                            int,              batchStride,
//                            void*,            pBuffer);

// SPARSE_API_DIRECT(Dgtsv2StridedBatch, please_write,  
//                            int,              m,
//                            const double*,    dl,
//                            const double*,    d,
//                            const double*,    du,
//                            double*,          x,
//                            int,              batchCount,
//                            int,              batchStride,
//                            void*,            pBuffer);

// SPARSE_API_DIRECT(Cgtsv2StridedBatch, please_write,  
//                            int,              m,
//                            const cuComplex*, dl,
//                            const cuComplex*, d,
//                            const cuComplex*, du,
//                            cuComplex*,       x,
//                            int,              batchCount,
//                            int,              batchStride,
//                            void*,            pBuffer);

// SPARSE_API_DIRECT(Zgtsv2StridedBatch, please_write,  
//                            int,                    m,
//                            const cuDoubleComplex*, dl,
//                            const cuDoubleComplex*, d,
//                            const cuDoubleComplex*, du,
//                            cuDoubleComplex*,       x,
//                            int,                    batchCount,
//                            int,                    batchStride,
//                            void*,                  pBuffer);

// SPARSE_API_DIRECT(SgtsvInterleavedBatch_bufferSizeExt, please_write, 
//                                             int,              algo,
//                                             int,              m,
//                                             const float*,     dl,
//                                             const float*,     d,
//                                             const float*,     du,
//                                             const float*,     x,
//                                             int,              batchCount,
//                                             size_t*,         pBufferSizeInBytes);

// SPARSE_API_DIRECT(DgtsvInterleavedBatch_bufferSizeExt, please_write, 
//                                          int,              algo,
//                                          int,              m,
//                                          const double*,    dl,
//                                          const double*,    d,
//                                          const double*,    du,
//                                          const double*,    x,
//                                          int,              batchCount,
//                                          size_t*,          pBufferSizeInBytes);

// SPARSE_API_DIRECT(CgtsvInterleavedBatch_bufferSizeExt, please_write, 
//                                             int,              algo,
//                                             int,              m,
//                                             const cuComplex*, dl,
//                                             const cuComplex*, d,
//                                             const cuComplex*, du,
//                                             const cuComplex*, x,
//                                             int,              batchCount,
//                                             size_t*,         pBufferSizeInBytes);

// SPARSE_API_DIRECT(ZgtsvInterleavedBatch_bufferSizeExt, please_write, 
//                                             int,                    algo,
//                                             int,                    m,
//                                             const cuDoubleComplex*, dl,
//                                             const cuDoubleComplex*, d,
//                                             const cuDoubleComplex*, du,
//                                             const cuDoubleComplex*, x,
//                                             int,                    batchCount,
//                                             size_t*,        pBufferSizeInBytes);

// SPARSE_API_DIRECT(SgtsvInterleavedBatch, please_write,   
//                               int,              algo,
//                               int,              m,
//                               float*,           dl,
//                               float*,           d,
//                               float*,           du,
//                               float*,           x,
//                               int,              batchCount,
//                               void*,            pBuffer);

// SPARSE_API_DIRECT(DgtsvInterleavedBatch, please_write,   
//                               int,              algo,
//                               int,              m,
//                               double*,          dl,
//                               double*,          d,
//                               double*,          du,
//                               double*,          x,
//                               int,              batchCount,
//                               void*,            pBuffer);

// SPARSE_API_DIRECT(CgtsvInterleavedBatch, please_write,   
//                               int,              algo,
//                               int,              m,
//                               cuComplex*,       dl,
//                               cuComplex*,       d,
//                               cuComplex*,       du,
//                               cuComplex*,       x,
//                               int,              batchCount,
//                               void*,            pBuffer);

// SPARSE_API_DIRECT(ZgtsvInterleavedBatch, please_write,   
//                               int,              algo,
//                               int,              m,
//                               cuDoubleComplex*, dl,
//                               cuDoubleComplex*, d,
//                               cuDoubleComplex*, du,
//                               cuDoubleComplex*, x,
//                               int,              batchCount,
//                               void*,            pBuffer);

// SPARSE_API_DIRECT(SgpsvInterleavedBatch_bufferSizeExt, please_write, 
//                                             int,              algo,
//                                             int,              m,
//                                             const float*,     ds,
//                                             const float*,     dl,
//                                             const float*,     d,
//                                             const float*,     du,
//                                             const float*,     dw,
//                                             const float*,     x,
//                                             int,              batchCount,
//                                             size_t*,         pBufferSizeInBytes);

// SPARSE_API_DIRECT(DgpsvInterleavedBatch_bufferSizeExt, please_write, 
//                                             int,              algo,
//                                             int,              m,
//                                             const double*,    ds,
//                                             const double*,    dl,
//                                             const double*,    d,
//                                             const double*,    du,
//                                             const double*,    dw,
//                                             const double*,    x,
//                                             int,              batchCount,
//                                             size_t*,         pBufferSizeInBytes);

// SPARSE_API_DIRECT(CgpsvInterleavedBatch_bufferSizeExt, please_write, 
//                                             int,              algo,
//                                             int,              m,
//                                             const cuComplex*, ds,
//                                             const cuComplex*, dl,
//                                             const cuComplex*, d,
//                                             const cuComplex*, du,
//                                             const cuComplex*, dw,
//                                             const cuComplex*, x,
//                                             int,              batchCount,
//                                             size_t*,         pBufferSizeInBytes);

// SPARSE_API_DIRECT(ZgpsvInterleavedBatch_bufferSizeExt, please_write, 
//                                             int,                    algo,
//                                             int,                    m,
//                                             const cuDoubleComplex*, ds,
//                                             const cuDoubleComplex*, dl,
//                                             const cuDoubleComplex*, d,
//                                             const cuDoubleComplex*, du,
//                                             const cuDoubleComplex*, dw,
//                                             const cuDoubleComplex*, x,
//                                             int,                    batchCount,
//                                             size_t*,         pBufferSizeInBytes);

// SPARSE_API_DIRECT(SgpsvInterleavedBatch, please_write,   
//                               int,              algo,
//                               int,              m,
//                               float*,           ds,
//                               float*,           dl,
//                               float*,           d,
//                               float*,           du,
//                               float*,           dw,
//                               float*,           x,
//                               int,              batchCount,
//                               void*,            pBuffer);

// SPARSE_API_DIRECT(DgpsvInterleavedBatch, please_write,   
//                               int,              algo,
//                               int,              m,
//                               double*,          ds,
//                               double*,          dl,
//                               double*,          d,
//                               double*,          du,
//                               double*,          dw,
//                               double*,          x,
//                               int,              batchCount,
//                               void*,            pBuffer);

// SPARSE_API_DIRECT(CgpsvInterleavedBatch, please_write,   
//                               int,              algo,
//                               int,              m,
//                               cuComplex*,       ds,
//                               cuComplex*,       dl,
//                               cuComplex*,       d,
//                               cuComplex*,       du,
//                               cuComplex*,       dw,
//                               cuComplex*,       x,
//                               int,              batchCount,
//                               void*,            pBuffer);

// SPARSE_API_DIRECT(ZgpsvInterleavedBatch, please_write,   
//                               int,              algo,
//                               int,              m,
//                               cuDoubleComplex*, ds,
//                               cuDoubleComplex*, dl,
//                               cuDoubleComplex*, d,
//                               cuDoubleComplex*, du,
//                               cuDoubleComplex*, dw,
//                               cuDoubleComplex*, x,
//                               int,              batchCount,
//                               void*,            pBuffer);
