
#include "common.h"

 /// Sparse Matrix Reordering
 

// SPARSE_API_DIRECT(Scsrcolor, please_write,   
//                   int,                      m,
//                   int,                      nnz,
//                   const cusparseMatDescr_t, descrA,
//                   const float*,              csrSortedValA,
//                   const int*,                csrSortedRowPtrA,
//                   const int*,                csrSortedColIndA,
//                   const float*,              fractionToColor,
//                   int*,                      ncolors,
//                   int*,                      coloring,
//                   int*,                      reordering,
//                   const cusparseColorInfo_t, info);

// SPARSE_API_DIRECT(Dcsrcolor, please_write,   
//                   int,                      m,
//                   int,                      nnz,
//                   const cusparseMatDescr_t, descrA,
//                   const double*,            csrSortedValA,
//                   const int*,               csrSortedRowPtrA,
//                   const int*,               csrSortedColIndA,
//                   const double*,            fractionToColor,
//                   int*,                     ncolors,
//                   int*,                     coloring,
//                   int*,                     reordering,
//                   const cusparseColorInfo_t, info);

// SPARSE_API_DIRECT(Ccsrcolor, please_write,   
//                   int,                      m,
//                   int,                      nnz,
//                   const cusparseMatDescr_t, descrA,
//                   const cuComplex*,          csrSortedValA,
//                   const int*,                csrSortedRowPtrA,
//                   const int*,                csrSortedColIndA,
//                   const float*,              fractionToColor,
//                   int*,                      ncolors,
//                   int*,                      coloring,
//                   int*,                      reordering,
//                   const cusparseColorInfo_t, info);

// SPARSE_API_DIRECT(Zcsrcolor, please_write,   
//                   int,                       m,
//                   int,                       nnz,
//                   const cusparseMatDescr_t,  descrA,
//                   const cuDoubleComplex*,    csrSortedValA,
//                   const int*,                csrSortedRowPtrA,
//                   const int*,                csrSortedColIndA,
//                   const double*,             fractionToColor,
//                   int*,                      ncolors,
//                   int*,                      coloring,
//                   int*,                      reordering,
//                   const cusparseColorInfo_t, info);

/// Sparse Matrix Format Conversion

// SPARSE_API_DIRECT(Snnz, please_write,    
//              cusparseDirection_t,      dirA,
//              int,                      m,
//              int,                      n,
//              const cusparseMatDescr_t, descrA,
//              const float*,             A,
//              int,                      lda,
//              int*,                     nnzPerRowCol,
//              int*,                     nnzTotalDevHostPtr);

// SPARSE_API_DIRECT(Dnnz, please_write,    
//              cusparseDirection_t,      dirA,
//              int,                      m,
//              int,                      n,
//              const cusparseMatDescr_t, descrA,
//              const double*,            A,
//              int,                      lda,
//              int*,                     nnzPerRowCol,
//              int*,                     nnzTotalDevHostPtr);

// SPARSE_API_DIRECT(Cnnz, please_write,    
//              cusparseDirection_t,      dirA,
//              int,                      m,
//              int,                      n,
//              const cusparseMatDescr_t, descrA,
//              const cuComplex*,         A,
//              int,                      lda,
//              int*,                     nnzPerRowCol,
//              int*,                     nnzTotalDevHostPtr);

// SPARSE_API_DIRECT(Znnz, please_write,    
//              cusparseDirection_t,      dirA,
//              int,                      m,
//              int,                      n,
//              const cusparseMatDescr_t, descrA,
//              const cuDoubleComplex*,   A,
//              int,                      lda,
//              int*,                     nnzPerRowCol,
//              int*,                     nnzTotalDevHostPtr);

// SPARSE_API_DIRECT(Snnz_compress, please_write,   
//                       int,                      m,
//                       const cusparseMatDescr_t, descr,
//                       const float*,             csrSortedValA,
//                       const int*,               csrSortedRowPtrA,
//                       int*,                     nnzPerRow,
//                       int*,                     nnzC,
//                       float,                    tol);

// SPARSE_API_DIRECT(Dnnz_compress, please_write,   
//                       int,                      m,
//                       const cusparseMatDescr_t, descr,
//                       const double*,            csrSortedValA,
//                       const int*,               csrSortedRowPtrA,
//                       int*,                     nnzPerRow,
//                       int*,                     nnzC,
//                       double,                   tol);

// SPARSE_API_DIRECT(Cnnz_compress, please_write,   
//                       int,                      m,
//                       const cusparseMatDescr_t, descr,
//                       const cuComplex*,         csrSortedValA,
//                       const int*,               csrSortedRowPtrA,
//                       int*,                     nnzPerRow,
//                       int*,                     nnzC,
//                       cuComplex,                tol);

// SPARSE_API_DIRECT(Znnz_compress, please_write,   
//                       int,                      m,
//                       const cusparseMatDescr_t, descr,
//                       const cuDoubleComplex*,   csrSortedValA,
//                       const int*,               csrSortedRowPtrA,
//                       int*,                     nnzPerRow,
//                       int*,                     nnzC,
//                       cuDoubleComplex,          tol);

// SPARSE_API_DIRECT(Scsr2csr_compress, please_write,   
//                           int,                      m,
//                           int,                      n,
//                           const cusparseMatDescr_t, descrA,
//                           const float*,             csrSortedValA,
//                           const int*,               csrSortedColIndA,
//                           const int*,               csrSortedRowPtrA,
//                           int,                      nnzA,
//                           const int*,               nnzPerRow,
//                           float*,                   csrSortedValC,
//                           int*,                     csrSortedColIndC,
//                           int*,                     csrSortedRowPtrC,
//                           float,                    tol);

// SPARSE_API_DIRECT(Dcsr2csr_compress, please_write,   
//                           int,                      m,
//                           int,                      n,
//                           const cusparseMatDescr_t, descrA,
//                           const double*,            csrSortedValA,
//                           const int*,               csrSortedColIndA,
//                           const int*,               csrSortedRowPtrA,
//                           int,                      nnzA,
//                           const int*,               nnzPerRow,
//                           double*,                  csrSortedValC,
//                           int*,                     csrSortedColIndC,
//                           int*,                     csrSortedRowPtrC,
//                           double,                   tol);

// SPARSE_API_DIRECT(Ccsr2csr_compress, please_write,   
//                           int,                      m,
//                           int,                      n,
//                           const cusparseMatDescr_t, descrA,
//                           const cuComplex*,         csrSortedValA,
//                           const int*,               csrSortedColIndA,
//                           const int*,               csrSortedRowPtrA,
//                           int,                      nnzA,
//                           const int*,               nnzPerRow,
//                           cuComplex*,               csrSortedValC,
//                           int*,                     csrSortedColIndC,
//                           int*,                     csrSortedRowPtrC,
//                           cuComplex,                tol);

// SPARSE_API_DIRECT(Zcsr2csr_compress, please_write,   
//                           int,                      m,
//                           int,                      n,
//                           const cusparseMatDescr_t, descrA,
//                           const cuDoubleComplex*,   csrSortedValA,
//                           const int*,               csrSortedColIndA,
//                           const int*,               csrSortedRowPtrA,
//                           int,                      nnzA,
//                           const int*,               nnzPerRow,
//                           cuDoubleComplex*,         csrSortedValC,
//                           int*,                     csrSortedColIndC,
//                           int*,                     csrSortedRowPtrC,
//                           cuDoubleComplex,          tol);

// SPARSE_API_DIRECT(Xcoo2csr, please_write,    
//                  const int*,          cooRowInd,
//                  int,                 nnz,
//                  int,                 m,
//                  int*,                csrSortedRowPtr,
//                  cusparseIndexBase_t, idxBase);

// SPARSE_API_DIRECT(Xcsr2coo, please_write,    
//                  const int*,          csrSortedRowPtr,
//                  int,                 nnz,
//                  int,                 m,
//                  int*,                cooRowInd,
//                  cusparseIndexBase_t, idxBase);

// SPARSE_API_DIRECT(Xcsr2bsrNnz, please_write, 
//                     cusparseDirection_t,      dirA,
//                     int,                      m,
//                     int,                      n,
//                     const cusparseMatDescr_t, descrA,
//                     const int*,               csrSortedRowPtrA,
//                     const int*,               csrSortedColIndA,
//                     int,                      blockDim,
//                     const cusparseMatDescr_t, descrC,
//                     int*,                     bsrSortedRowPtrC,
//                     int*,                     nnzTotalDevHostPtr);

// SPARSE_API_DIRECT(Scsr2bsr, please_write,    
//                  cusparseDirection_t,      dirA,
//                  int,                      m,
//                  int,                      n,
//                  const cusparseMatDescr_t, descrA,
//                  const float*,             csrSortedValA,
//                  const int*,               csrSortedRowPtrA,
//                  const int*,               csrSortedColIndA,
//                  int,                      blockDim,
//                  const cusparseMatDescr_t, descrC,
//                  float*,                   bsrSortedValC,
//                  int*,                     bsrSortedRowPtrC,
//                  int*,                     bsrSortedColIndC);

// SPARSE_API_DIRECT(Dcsr2bsr, please_write,    
//                  cusparseDirection_t,      dirA,
//                  int,                      m,
//                  int,                      n,
//                  const cusparseMatDescr_t, descrA,
//                  const double*,            csrSortedValA,
//                  const int*,               csrSortedRowPtrA,
//                  const int*,               csrSortedColIndA,
//                  int,                      blockDim,
//                  const cusparseMatDescr_t, descrC,
//                  double*,                  bsrSortedValC,
//                  int*,                     bsrSortedRowPtrC,
//                  int*,                     bsrSortedColIndC);

// SPARSE_API_DIRECT(Ccsr2bsr, please_write,    
//                  cusparseDirection_t,      dirA,
//                  int,                      m,
//                  int,                      n,
//                  const cusparseMatDescr_t, descrA,
//                  const cuComplex*,         csrSortedValA,
//                  const int*,               csrSortedRowPtrA,
//                  const int*,               csrSortedColIndA,
//                  int,                      blockDim,
//                  const cusparseMatDescr_t, descrC,
//                  cuComplex*,               bsrSortedValC,
//                  int*,                     bsrSortedRowPtrC,
//                  int*,                     bsrSortedColIndC);

// SPARSE_API_DIRECT(Zcsr2bsr, please_write,    
//                  cusparseDirection_t,      dirA,
//                  int,                      m,
//                  int,                      n,
//                  const cusparseMatDescr_t, descrA,
//                  const cuDoubleComplex*,   csrSortedValA,
//                  const int*,               csrSortedRowPtrA,
//                  const int*,               csrSortedColIndA,
//                  int,                      blockDim,
//                  const cusparseMatDescr_t, descrC,
//                  cuDoubleComplex*,         bsrSortedValC,
//                  int*,                     bsrSortedRowPtrC,
//                  int*,                     bsrSortedColIndC);

// SPARSE_API_DIRECT(Sbsr2csr, please_write,    
//                  cusparseDirection_t,      dirA,
//                  int,                      mb,
//                  int,                      nb,
//                  const cusparseMatDescr_t, descrA,
//                  const float*,             bsrSortedValA,
//                  const int*,               bsrSortedRowPtrA,
//                  const int*,               bsrSortedColIndA,
//                  int,                      blockDim,
//                  const cusparseMatDescr_t, descrC,
//                  float*,                   csrSortedValC,
//                  int*,                     csrSortedRowPtrC,
//                  int*,                     csrSortedColIndC);

// SPARSE_API_DIRECT(Dbsr2csr, please_write,    
//                  cusparseDirection_t,      dirA,
//                  int,                      mb,
//                  int,                      nb,
//                  const cusparseMatDescr_t, descrA,
//                  const double*,            bsrSortedValA,
//                  const int*,               bsrSortedRowPtrA,
//                  const int*,               bsrSortedColIndA,
//                  int,                      blockDim,
//                  const cusparseMatDescr_t, descrC,
//                  double*,                  csrSortedValC,
//                  int*,                     csrSortedRowPtrC,
//                  int*,                     csrSortedColIndC);

// SPARSE_API_DIRECT(Cbsr2csr, please_write,    
//                  cusparseDirection_t,      dirA,
//                  int,                      mb,
//                  int,                      nb,
//                  const cusparseMatDescr_t, descrA,
//                  const cuComplex*,         bsrSortedValA,
//                  const int*,               bsrSortedRowPtrA,
//                  const int*,               bsrSortedColIndA,
//                  int,                      blockDim,
//                  const cusparseMatDescr_t, descrC,
//                  cuComplex*,               csrSortedValC,
//                  int*,                     csrSortedRowPtrC,
//                  int*,                     csrSortedColIndC);

// SPARSE_API_DIRECT(Zbsr2csr, please_write,    
//                  cusparseDirection_t,      dirA,
//                  int,                      mb,
//                  int,                      nb,
//                  const cusparseMatDescr_t, descrA,
//                  const cuDoubleComplex*,   bsrSortedValA,
//                  const int*,               bsrSortedRowPtrA,
//                  const int*,               bsrSortedColIndA,
//                  int,                      blockDim,
//                  const cusparseMatDescr_t, descrC,
//                  cuDoubleComplex*,         csrSortedValC,
//                  int*,                     csrSortedRowPtrC,
//                  int*,                     csrSortedColIndC);

// SPARSE_API_DIRECT(Sgebsr2gebsc_bufferSize, please_write, 
//                                 int,              mb,
//                                 int,              nb,
//                                 int,              nnzb,
//                                 const float*,     bsrSortedVal,
//                                 const int*,       bsrSortedRowPtr,
//                                 const int*,       bsrSortedColInd,
//                                 int,              rowBlockDim,
//                                 int,              colBlockDim,
//                                 int*,             pBufferSizeInBytes);

// SPARSE_API_DIRECT(Dgebsr2gebsc_bufferSize, please_write, 
//                                 int,              mb,
//                                 int,              nb,
//                                 int,              nnzb,
//                                 const double*,    bsrSortedVal,
//                                 const int*,       bsrSortedRowPtr,
//                                 const int*,       bsrSortedColInd,
//                                 int,              rowBlockDim,
//                                 int,              colBlockDim,
//                                 int*,             pBufferSizeInBytes);

// SPARSE_API_DIRECT(Cgebsr2gebsc_bufferSize, please_write, 
//                                 int,              mb,
//                                 int,              nb,
//                                 int,              nnzb,
//                                 const cuComplex*, bsrSortedVal,
//                                 const int*,       bsrSortedRowPtr,
//                                 const int*,       bsrSortedColInd,
//                                 int,              rowBlockDim,
//                                 int,              colBlockDim,
//                                 int*,             pBufferSizeInBytes);

// SPARSE_API_DIRECT(Zgebsr2gebsc_bufferSize, please_write, 
//                                 int,                    mb,
//                                 int,                    nb,
//                                 int,                    nnzb,
//                                 const cuDoubleComplex*, bsrSortedVal,
//                                 const int*,             bsrSortedRowPtr,
//                                 const int*,             bsrSortedColInd,
//                                 int,                    rowBlockDim,
//                                 int,                    colBlockDim,
//                                 int*,                   pBufferSizeInBytes);

// SPARSE_API_DIRECT(Sgebsr2gebsc_bufferSizeExt, please_write,  
//                                    int,              mb,
//                                    int,              nb,
//                                    int,              nnzb,
//                                    const float*,     bsrSortedVal,
//                                    const int*,       bsrSortedRowPtr,
//                                    const int*,       bsrSortedColInd,
//                                    int,              rowBlockDim,
//                                    int,              colBlockDim,
//                                    size_t*,          pBufferSize);

// SPARSE_API_DIRECT(Dgebsr2gebsc_bufferSizeExt, please_write,  
//                                    int,              mb,
//                                    int,              nb,
//                                    int,              nnzb,
//                                    const double*,    bsrSortedVal,
//                                    const int*,       bsrSortedRowPtr,
//                                    const int*,       bsrSortedColInd,
//                                    int,              rowBlockDim,
//                                    int,              colBlockDim,
//                                    size_t*,          pBufferSize);

// SPARSE_API_DIRECT(Cgebsr2gebsc_bufferSizeExt, please_write,  
//                                    int,              mb,
//                                    int,              nb,
//                                    int,              nnzb,
//                                    const cuComplex*, bsrSortedVal,
//                                    const int*,       bsrSortedRowPtr,
//                                    const int*,       bsrSortedColInd,
//                                    int,              rowBlockDim,
//                                    int,              colBlockDim,
//                                    size_t*,          pBufferSize);

// SPARSE_API_DIRECT(Zgebsr2gebsc_bufferSizeExt, please_write,  
//                                    int,                    mb,
//                                    int,                    nb,
//                                    int,                    nnzb,
//                                    const cuDoubleComplex*, bsrSortedVal,
//                                    const int*,             bsrSortedRowPtr,
//                                    const int*,             bsrSortedColInd,
//                                    int,                    rowBlockDim,
//                                    int,                    colBlockDim,
//                                    size_t*,                pBufferSize);

// SPARSE_API_DIRECT(Sgebsr2gebsc, please_write,    
//                      int,              mb,
//                      int,              nb,
//                      int,              nnzb,
//                      const float*,     bsrSortedVal,
//                      const int*, bsrSortedRowPtr,
//                      const int*, bsrSortedColInd,
//                      int,        rowBlockDim,
//                      int,        colBlockDim,
//                      float*,     bscVal,
//                      int*,       bscRowInd,
//                      int*,       bscColPtr,
//                      cusparseAction_t, copyValues,
//                      cusparseIndexBase_t, idxBase,
//                      void*,               pBuffer);

// SPARSE_API_DIRECT(Dgebsr2gebsc, please_write,    
//                      int,                 mb,
//                      int,                 nb,
//                      int,                 nnzb,
//                      const double*,       bsrSortedVal,
//                      const int*,          bsrSortedRowPtr,
//                      const int*,          bsrSortedColInd,
//                      int,                 rowBlockDim,
//                      int,                 colBlockDim,
//                      double*,             bscVal,
//                      int*,                bscRowInd,
//                      int*,                bscColPtr,
//                      cusparseAction_t,    copyValues,
//                      cusparseIndexBase_t, idxBase,
//                      void*,               pBuffer);

// SPARSE_API_DIRECT(Cgebsr2gebsc, please_write,    
//                      int,                 mb,
//                      int,                 nb,
//                      int,                 nnzb,
//                      const cuComplex*,    bsrSortedVal,
//                      const int*,          bsrSortedRowPtr,
//                      const int*,          bsrSortedColInd,
//                      int,                 rowBlockDim,
//                      int,                 colBlockDim,
//                      cuComplex*,          bscVal,
//                      int*,                bscRowInd,
//                      int*,                bscColPtr,
//                      cusparseAction_t,    copyValues,
//                      cusparseIndexBase_t, idxBase,
//                      void*,               pBuffer);

// SPARSE_API_DIRECT(Zgebsr2gebsc, please_write,    
//                      int,                    mb,
//                      int,                    nb,
//                      int,                    nnzb,
//                      const cuDoubleComplex*, bsrSortedVal,
//                      const int*,             bsrSortedRowPtr,
//                      const int*,             bsrSortedColInd,
//                      int,                    rowBlockDim,
//                      int,                    colBlockDim,
//                      cuDoubleComplex*,       bscVal,
//                      int*,                   bscRowInd,
//                      int*,                   bscColPtr,
//                      cusparseAction_t,       copyValues,
//                      cusparseIndexBase_t,    idxBase,
//                      void*,                  pBuffer);

// SPARSE_API_DIRECT(Xgebsr2csr, please_write,  
//                    cusparseDirection_t,      dirA,
//                    int,                      mb,
//                    int,                      nb,
//                    const cusparseMatDescr_t, descrA,
//                    const int*,               bsrSortedRowPtrA,
//                    const int*,               bsrSortedColIndA,
//                    int,                      rowBlockDim,
//                    int,                      colBlockDim,
//                    const cusparseMatDescr_t, descrC,
//                    int*,                     csrSortedRowPtrC,
//                    int*,                     csrSortedColIndC);

// SPARSE_API_DIRECT(Sgebsr2csr, please_write,  
//                    cusparseDirection_t,      dirA,
//                    int,                      mb,
//                    int,                      nb,
//                    const cusparseMatDescr_t, descrA,
//                    const float*,             bsrSortedValA,
//                    const int*,               bsrSortedRowPtrA,
//                    const int*,               bsrSortedColIndA,
//                    int,                      rowBlockDim,
//                    int,                      colBlockDim,
//                    const cusparseMatDescr_t, descrC,
//                    float*,                   csrSortedValC,
//                    int*,                     csrSortedRowPtrC,
//                    int*,                     csrSortedColIndC);

// SPARSE_API_DIRECT(Dgebsr2csr, please_write,  
//                    cusparseDirection_t,      dirA,
//                    int,                      mb,
//                    int,                      nb,
//                    const cusparseMatDescr_t, descrA,
//                    const double*,            bsrSortedValA,
//                    const int*,               bsrSortedRowPtrA,
//                    const int*,               bsrSortedColIndA,
//                    int,                      rowBlockDim,
//                    int,                      colBlockDim,
//                    const cusparseMatDescr_t, descrC,
//                    double*,                  csrSortedValC,
//                    int*,                     csrSortedRowPtrC,
//                    int*,                     csrSortedColIndC);

// SPARSE_API_DIRECT(Cgebsr2csr, please_write,  
//                    cusparseDirection_t,      dirA,
//                    int,                      mb,
//                    int,                      nb,
//                    const cusparseMatDescr_t, descrA,
//                    const cuComplex*,         bsrSortedValA,
//                    const int*,               bsrSortedRowPtrA,
//                    const int*,               bsrSortedColIndA,
//                    int,                      rowBlockDim,
//                    int,                      colBlockDim,
//                    const cusparseMatDescr_t, descrC,
//                    cuComplex*,               csrSortedValC,
//                    int*,                     csrSortedRowPtrC,
//                    int*,                     csrSortedColIndC);

// SPARSE_API_DIRECT(Zgebsr2csr, please_write,  
//                    cusparseDirection_t,      dirA,
//                    int,                      mb,
//                    int,                      nb,
//                    const cusparseMatDescr_t, descrA,
//                    const cuDoubleComplex*,   bsrSortedValA,
//                    const int*,               bsrSortedRowPtrA,
//                    const int*,               bsrSortedColIndA,
//                    int,                      rowBlockDim,
//                    int,                      colBlockDim,
//                    const cusparseMatDescr_t, descrC,
//                    cuDoubleComplex*,         csrSortedValC,
//                    int*,                     csrSortedRowPtrC,
//                    int*,                     csrSortedColIndC);

// SPARSE_API_DIRECT(Scsr2gebsr_bufferSize, please_write,   
//                               cusparseDirection_t,      dirA,
//                               int,                      m,
//                               int,                      n,
//                               const cusparseMatDescr_t, descrA,
//                               const float*,             csrSortedValA,
//                               const int*,               csrSortedRowPtrA,
//                               const int*,               csrSortedColIndA,
//                               int,                      rowBlockDim,
//                               int,                      colBlockDim,
//                               int*,                     pBufferSizeInBytes);

// SPARSE_API_DIRECT(Dcsr2gebsr_bufferSize, please_write,   
//                               cusparseDirection_t,      dirA,
//                               int,                      m,
//                               int,                      n,
//                               const cusparseMatDescr_t, descrA,
//                               const double*,            csrSortedValA,
//                               const int*,               csrSortedRowPtrA,
//                               const int*,               csrSortedColIndA,
//                               int,                      rowBlockDim,
//                               int,                      colBlockDim,
//                               int*,                     pBufferSizeInBytes);

// SPARSE_API_DIRECT(Ccsr2gebsr_bufferSize, please_write,   
//                               cusparseDirection_t,      dirA,
//                               int,                      m,
//                               int,                      n,
//                               const cusparseMatDescr_t, descrA,
//                               const cuComplex*,         csrSortedValA,
//                               const int*,               csrSortedRowPtrA,
//                               const int*,               csrSortedColIndA,
//                               int,                      rowBlockDim,
//                               int,                      colBlockDim,
//                               int*,                     pBufferSizeInBytes);

// SPARSE_API_DIRECT(Zcsr2gebsr_bufferSize, please_write,   
//                               cusparseDirection_t,      dirA,
//                               int,                      m,
//                               int,                      n,
//                               const cusparseMatDescr_t, descrA,
//                               const cuDoubleComplex*,   csrSortedValA,
//                               const int*,               csrSortedRowPtrA,
//                               const int*,               csrSortedColIndA,
//                               int,                      rowBlockDim,
//                               int,                      colBlockDim,
//                               int*,                     pBufferSizeInBytes);

// SPARSE_API_DIRECT(Scsr2gebsr_bufferSizeExt, please_write,    
//                                  cusparseDirection_t,      dirA,
//                                  int,                      m,
//                                  int,                      n,
//                                  const cusparseMatDescr_t, descrA,
//                                  const float*,             csrSortedValA,
//                                  const int*,               csrSortedRowPtrA,
//                                  const int*,               csrSortedColIndA,
//                                  int,                      rowBlockDim,
//                                  int,                      colBlockDim,
//                                  size_t*,                  pBufferSize);

// SPARSE_API_DIRECT(Dcsr2gebsr_bufferSizeExt, please_write,    
//                                  cusparseDirection_t,      dirA,
//                                  int,                      m,
//                                  int,                      n,
//                                  const cusparseMatDescr_t, descrA,
//                                  const double*,            csrSortedValA,
//                                  const int*,               csrSortedRowPtrA,
//                                  const int*,               csrSortedColIndA,
//                                  int,                      rowBlockDim,
//                                  int,                      colBlockDim,
//                                  size_t*,                  pBufferSize);

// SPARSE_API_DIRECT(Ccsr2gebsr_bufferSizeExt, please_write,    
//                                  cusparseDirection_t,      dirA,
//                                  int,                      m,
//                                  int,                      n,
//                                  const cusparseMatDescr_t, descrA,
//                                  const cuComplex*,         csrSortedValA,
//                                  const int*,               csrSortedRowPtrA,
//                                  const int*,               csrSortedColIndA,
//                                  int,                      rowBlockDim,
//                                  int,                      colBlockDim,
//                                  size_t*,                  pBufferSize);

// SPARSE_API_DIRECT(Zcsr2gebsr_bufferSizeExt, please_write,    
//                                  cusparseDirection_t,      dirA,
//                                  int,                      m,
//                                  int,                      n,
//                                  const cusparseMatDescr_t, descrA,
//                                  const cuDoubleComplex*,   csrSortedValA,
//                                  const int*,               csrSortedRowPtrA,
//                                  const int*,               csrSortedColIndA,
//                                  int,                      rowBlockDim,
//                                  int,                      colBlockDim,
//                                  size_t*,                  pBufferSize);

// SPARSE_API_DIRECT(Xcsr2gebsrNnz, please_write,   
//                       cusparseDirection_t,      dirA,
//                       int,                      m,
//                       int,                      n,
//                       const cusparseMatDescr_t, descrA,
//                       const int*,               csrSortedRowPtrA,
//                       const int*,               csrSortedColIndA,
//                       const cusparseMatDescr_t, descrC,
//                       int*,                     bsrSortedRowPtrC,
//                       int,                      rowBlockDim,
//                       int,                      colBlockDim,
//                       int*,                     nnzTotalDevHostPtr,
//                       void*,                    pBuffer);

// SPARSE_API_DIRECT(Scsr2gebsr, please_write,  
//                    cusparseDirection_t,      dirA,
//                    int,                      m,
//                    int,                      n,
//                    const cusparseMatDescr_t, descrA,
//                    const float*,             csrSortedValA,
//                    const int*,               csrSortedRowPtrA,
//                    const int*,               csrSortedColIndA,
//                    const cusparseMatDescr_t, descrC,
//                    float*,                   bsrSortedValC,
//                    int*,                     bsrSortedRowPtrC,
//                    int*,                     bsrSortedColIndC,
//                    int,                      rowBlockDim,
//                    int,                      colBlockDim,
//                    void*,                    pBuffer);

// SPARSE_API_DIRECT(Dcsr2gebsr, please_write,  
//                    cusparseDirection_t,      dirA,
//                    int,                      m,
//                    int,                      n,
//                    const cusparseMatDescr_t, descrA,
//                    const double*,            csrSortedValA,
//                    const int*,               csrSortedRowPtrA,
//                    const int*,               csrSortedColIndA,
//                    const cusparseMatDescr_t, descrC,
//                    double*,                  bsrSortedValC,
//                    int*,                     bsrSortedRowPtrC,
//                    int*,                     bsrSortedColIndC,
//                    int,                      rowBlockDim,
//                    int,                      colBlockDim,
//                    void*,                    pBuffer);

// SPARSE_API_DIRECT(Ccsr2gebsr, please_write,  
//                    cusparseDirection_t,      dirA,
//                    int,                      m,
//                    int,                      n,
//                    const cusparseMatDescr_t, descrA,
//                    const cuComplex*,         csrSortedValA,
//                    const int*,               csrSortedRowPtrA,
//                    const int*,               csrSortedColIndA,
//                    const cusparseMatDescr_t, descrC,
//                    cuComplex*,               bsrSortedValC,
//                    int*,                     bsrSortedRowPtrC,
//                    int*,                     bsrSortedColIndC,
//                    int,                      rowBlockDim,
//                    int,                      colBlockDim,
//                    void*,                    pBuffer);

// SPARSE_API_DIRECT(Zcsr2gebsr, please_write,  
//                    cusparseDirection_t,      dirA,
//                    int,                      m,
//                    int,                      n,
//                    const cusparseMatDescr_t, descrA,
//                    const cuDoubleComplex*,   csrSortedValA,
//                    const int*,               csrSortedRowPtrA,
//                    const int*,               csrSortedColIndA,
//                    const cusparseMatDescr_t, descrC,
//                    cuDoubleComplex*,         bsrSortedValC,
//                    int*,                     bsrSortedRowPtrC,
//                    int*,                     bsrSortedColIndC,
//                    int,                      rowBlockDim,
//                    int,                      colBlockDim,
//                    void*,                    pBuffer);

// SPARSE_API_DIRECT(Sgebsr2gebsr_bufferSize, please_write, 
//                                 cusparseDirection_t,      dirA,
//                                 int,                      mb,
//                                 int,                      nb,
//                                 int,                      nnzb,
//                                 const cusparseMatDescr_t, descrA,
//                                 const float*,             bsrSortedValA,
//                                 const int*,               bsrSortedRowPtrA,
//                                 const int*,               bsrSortedColIndA,
//                                 int,                      rowBlockDimA,
//                                 int,                      colBlockDimA,
//                                 int,                      rowBlockDimC,
//                                 int,                      colBlockDimC,
//                                 int*,                     pBufferSizeInBytes);

// SPARSE_API_DIRECT(Dgebsr2gebsr_bufferSize, please_write, 
//                                 cusparseDirection_t,      dirA,
//                                 int,                      mb,
//                                 int,                      nb,
//                                 int,                      nnzb,
//                                 const cusparseMatDescr_t, descrA,
//                                 const double*,            bsrSortedValA,
//                                 const int*,               bsrSortedRowPtrA,
//                                 const int*,               bsrSortedColIndA,
//                                 int,                      rowBlockDimA,
//                                 int,                      colBlockDimA,
//                                 int,                      rowBlockDimC,
//                                 int,                      colBlockDimC,
//                                 int*,                     pBufferSizeInBytes);

// SPARSE_API_DIRECT(Cgebsr2gebsr_bufferSize, please_write, 
//                                 cusparseDirection_t,      dirA,
//                                 int,                      mb,
//                                 int,                      nb,
//                                 int,                      nnzb,
//                                 const cusparseMatDescr_t, descrA,
//                                 const cuComplex*,         bsrSortedValA,
//                                 const int*,               bsrSortedRowPtrA,
//                                 const int*,               bsrSortedColIndA,
//                                 int,                      rowBlockDimA,
//                                 int,                      colBlockDimA,
//                                 int,                      rowBlockDimC,
//                                 int,                      colBlockDimC,
//                                 int*,                     pBufferSizeInBytes);

// SPARSE_API_DIRECT(Zgebsr2gebsr_bufferSize, please_write, 
//                                 cusparseDirection_t,      dirA,
//                                 int,                      mb,
//                                 int,                      nb,
//                                 int,                      nnzb,
//                                 const cusparseMatDescr_t, descrA,
//                                 const cuDoubleComplex*,   bsrSortedValA,
//                                 const int*,               bsrSortedRowPtrA,
//                                 const int*,               bsrSortedColIndA,
//                                 int,                      rowBlockDimA,
//                                 int,                      colBlockDimA,
//                                 int,                      rowBlockDimC,
//                                 int,                      colBlockDimC,
//                                 int*,                     pBufferSizeInBytes);

// SPARSE_API_DIRECT(Sgebsr2gebsr_bufferSizeExt, please_write,  
//                                    cusparseDirection_t,      dirA,
//                                    int,                      mb,
//                                    int,                      nb,
//                                    int,                      nnzb,
//                                    const cusparseMatDescr_t, descrA,
//                                    const float*,             bsrSortedValA,
//                                    const int*,               bsrSortedRowPtrA,
//                                    const int*,               bsrSortedColIndA,
//                                    int,                      rowBlockDimA,
//                                    int,                      colBlockDimA,
//                                    int,                      rowBlockDimC,
//                                    int,                      colBlockDimC,
//                                    size_t*,                  pBufferSize);

// SPARSE_API_DIRECT(Dgebsr2gebsr_bufferSizeExt, please_write,  
//                                    cusparseDirection_t,      dirA,
//                                    int,                      mb,
//                                    int,                      nb,
//                                    int,                      nnzb,
//                                    const cusparseMatDescr_t, descrA,
//                                    const double*,            bsrSortedValA,
//                                    const int*,               bsrSortedRowPtrA,
//                                    const int*,               bsrSortedColIndA,
//                                    int,                      rowBlockDimA,
//                                    int,                      colBlockDimA,
//                                    int,                      rowBlockDimC,
//                                    int,                      colBlockDimC,
//                                    size_t*,                  pBufferSize);

// SPARSE_API_DIRECT(Cgebsr2gebsr_bufferSizeExt, please_write,  
//                                    cusparseDirection_t,      dirA,
//                                    int,                      mb,
//                                    int,                      nb,
//                                    int,                      nnzb,
//                                    const cusparseMatDescr_t, descrA,
//                                    const cuComplex*,         bsrSortedValA,
//                                    const int*,               bsrSortedRowPtrA,
//                                    const int*,               bsrSortedColIndA,
//                                    int,                      rowBlockDimA,
//                                    int,                      colBlockDimA,
//                                    int,                      rowBlockDimC,
//                                    int,                      colBlockDimC,
//                                    size_t*,                  pBufferSize);

// SPARSE_API_DIRECT(Zgebsr2gebsr_bufferSizeExt, please_write,  
//                                    cusparseDirection_t,      dirA,
//                                    int,                      mb,
//                                    int,                      nb,
//                                    int,                      nnzb,
//                                    const cusparseMatDescr_t, descrA,
//                                    const cuDoubleComplex*,   bsrSortedValA,
//                                    const int*,               bsrSortedRowPtrA,
//                                    const int*,               bsrSortedColIndA,
//                                    int,                      rowBlockDimA,
//                                    int,                      colBlockDimA,
//                                    int,                      rowBlockDimC,
//                                    int,                      colBlockDimC,
//                                    size_t*,                  pBufferSize);

// SPARSE_API_DIRECT(Xgebsr2gebsrNnz, please_write, 
//                         cusparseDirection_t,      dirA,
//                         int,                      mb,
//                         int,                      nb,
//                         int,                      nnzb,
//                         const cusparseMatDescr_t, descrA,
//                         const int*,               bsrSortedRowPtrA,
//                         const int*,               bsrSortedColIndA,
//                         int,                      rowBlockDimA,
//                         int,                      colBlockDimA,
//                         const cusparseMatDescr_t, descrC,
//                         int*,                     bsrSortedRowPtrC,
//                         int,                      rowBlockDimC,
//                         int,                      colBlockDimC,
//                         int*,                     nnzTotalDevHostPtr,
//                         void*,                    pBuffer);

// SPARSE_API_DIRECT(Sgebsr2gebsr, please_write,    
//                      cusparseDirection_t,      dirA,
//                      int,                      mb,
//                      int,                      nb,
//                      int,                      nnzb,
//                      const cusparseMatDescr_t, descrA,
//                      const float*,             bsrSortedValA,
//                      const int*,               bsrSortedRowPtrA,
//                      const int*,               bsrSortedColIndA,
//                      int,                      rowBlockDimA,
//                      int,                      colBlockDimA,
//                      const cusparseMatDescr_t, descrC,
//                      float*,                   bsrSortedValC,
//                      int*,                     bsrSortedRowPtrC,
//                      int*,                     bsrSortedColIndC,
//                      int,                      rowBlockDimC,
//                      int,                      colBlockDimC,
//                      void*,                    pBuffer);

// SPARSE_API_DIRECT(Dgebsr2gebsr, please_write,    
//                      cusparseDirection_t,      dirA,
//                      int,                      mb,
//                      int,                      nb,
//                      int,                      nnzb,
//                      const cusparseMatDescr_t, descrA,
//                      const double*,            bsrSortedValA,
//                      const int*,               bsrSortedRowPtrA,
//                      const int*,               bsrSortedColIndA,
//                      int,                      rowBlockDimA,
//                      int,                      colBlockDimA,
//                      const cusparseMatDescr_t, descrC,
//                      double*,                  bsrSortedValC,
//                      int*,                     bsrSortedRowPtrC,
//                      int*,                     bsrSortedColIndC,
//                      int,                      rowBlockDimC,
//                      int,                      colBlockDimC,
//                      void*,                    pBuffer);

// SPARSE_API_DIRECT(Cgebsr2gebsr, please_write,    
//                      cusparseDirection_t,      dirA,
//                      int,                      mb,
//                      int,                      nb,
//                      int,                      nnzb,
//                      const cusparseMatDescr_t, descrA,
//                      const cuComplex*,         bsrSortedValA,
//                      const int*,               bsrSortedRowPtrA,
//                      const int*,               bsrSortedColIndA,
//                      int,                      rowBlockDimA,
//                      int,                      colBlockDimA,
//                      const cusparseMatDescr_t, descrC,
//                      cuComplex*,               bsrSortedValC,
//                      int*,                     bsrSortedRowPtrC,
//                      int*,                     bsrSortedColIndC,
//                      int,                      rowBlockDimC,
//                      int,                      colBlockDimC,
//                      void*,                    pBuffer);

// SPARSE_API_DIRECT(Zgebsr2gebsr, please_write,    
//                      cusparseDirection_t,      dirA,
//                      int,                      mb,
//                      int,                      nb,
//                      int,                      nnzb,
//                      const cusparseMatDescr_t, descrA,
//                      const cuDoubleComplex*,   bsrSortedValA,
//                      const int*,               bsrSortedRowPtrA,
//                      const int*,               bsrSortedColIndA,
//                      int,                      rowBlockDimA,
//                      int,                      colBlockDimA,
//                      const cusparseMatDescr_t, descrC,
//                      cuDoubleComplex*,         bsrSortedValC,
//                      int*,                     bsrSortedRowPtrC,
//                      int*,                     bsrSortedColIndC,
//                      int,                      rowBlockDimC,
//                      int,                      colBlockDimC,
//                      void*,                    pBuffer);
